### ISSUE TITLE
Remove ResizeObserver pollyfill

### ISSUE THREAD

**Issue by ChrisShank** [samthor/viz-observer#1]
It's a small change but I think it would be might removing the ResizeObserver pollyfill and maybe the IntersectionObserver check for size . Not sure if it would be a breaking change (this library currently has low usage, but its on the rise of recent 📈), but browser support for both of these is standard, particularly with IE support ending last year. Happy to contribute!

**Comment by samthor** [comment]
For sure, this library was written at a different time, so removing ancient browser support is fine with me.

Feel free to send a PR or I can look at it sometime.

**Comment by ChrisShank** [comment]
Sweet I've already working on this!

I'm also looking to rewrite in typescript and looking into some perf improvements as well. For this library to scale well, we need to to be as optimized as we can! It might cause a breaking API changes though 😅

See #3
